### ISSUE TITLE
Too many connections error

### ISSUE THREAD

**Issue by mcverticchio** [KalenAnson/kiddy#3]
This error appears after I have been running my node server for a while.  I have to stop and restart the server to make the error go away.  

```
Error: ER_CON_COUNT_ERROR: Too many connections
    at Handshake.Sequence._packetToError (/Users/carolineverticchio/Desktop/reportingApp/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Handshake.ErrorPacket (/Users/carolineverticchio/Desktop/reportingApp/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)
    at Protocol._parsePacket (/Users/carolineverticchio/Desktop/reportingApp/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/Users/carolineverticchio/Desktop/reportingApp/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/carolineverticchio/Desktop/reportingApp/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/carolineverticchio/Desktop/reportingApp/node_modules/mysql/lib/Connection.js:103:28)
    at Socket.emit (events.js:180:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onread (net.js:578:20)
---------------------------------------------
    at Socket.Readable.on (_stream_readable.js:779:35)
    at PoolConnection.connect (/Users/carolineverticchio/Desktop/reportingApp/node_modules/mysql/lib/Connection.js:102:18)
    at Pool.getConnection (/Users/carolineverticchio/Desktop/reportingApp/node_modules/mysql/lib/Pool.js:48:16)
    at Promise.post (/Users/carolineverticchio/Desktop/reportingApp/node_modules/q/q.js:1181:36)
    at Promise.promise.promiseDispatch (/Users/carolineverticchio/Desktop/reportingApp/node_modules/q/q.js:808:41)
    at /Users/carolineverticchio/Desktop/reportingApp/node_modules/q/q.js:1411:14
    at runSingle (/Users/carolineverticchio/Desktop/reportingApp/node_modules/q/q.js:137:13)
    at flush (/Users/carolineverticchio/Desktop/reportingApp/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:112:11)
---------------------------------------------
    at requestTick (/Users/carolineverticchio/Desktop/reportingApp/node_modules/q/q.js:197:21)
    at Function.nextTick (/Users/carolineverticchio/Desktop/reportingApp/node_modules/q/q.js:180:13)
    at Promise.then (/Users/carolineverticchio/Desktop/reportingApp/node_modules/q/q.js:876:7)
    at /Users/carolineverticchio/Desktop/reportingApp/node_modules/kiddy/lib/kiddy.js:44:4
    at Function.promise (/Users/carolineverticchio/Desktop/reportingApp/node_modules/q/q.js:702:9)
    at Object.exports.touch (/Users/carolineverticchio/Desktop/reportingApp/node_modules/kiddy/lib/kiddy.js:42:11)
    at exports.getUsers (/Users/carolineverticchio/Desktop/reportingApp/lib/admin/controllers/admin.js:70:8)
    at Layer.handle [as handle_request] (/Users/carolineverticchio/Desktop/reportingApp/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/carolineverticchio/Desktop/reportingApp/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/carolineverticchio/Desktop/reportingApp/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/carolineverticchio/Desktop/reportingApp/node_modules/express/lib/router/layer.js:95:5)
    at /Users/carolineverticchio/Desktop/reportingApp/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/carolineverticchio/Desktop/reportingApp/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/carolineverticchio/Desktop/reportingApp/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/Users/carolineverticchio/Desktop/reportingApp/node_modules/express/lib/router/index.js:174:3)
---------------------------------------------
    at serveStatic (/Users/carolineverticchio/Desktop/reportingApp/node_modules/serve-static/index.js:115:12)
    at Layer.handle [as handle_request] (/Users/carolineverticchio/Desktop/reportingApp/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/carolineverticchio/Desktop/reportingApp/node_modules/express/lib/router/index.js:317:13)
    at /Users/carolineverticchio/Desktop/reportingApp/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/carolineverticchio/Desktop/reportingApp/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/carolineverticchio/Desktop/reportingApp/node_modules/express/lib/router/index.js:275:10)
    at /Users/carolineverticchio/Desktop/reportingApp/node_modules/less-middleware/lib/middleware.js:317:14
    at Layer.handle [as handle_request] (/Users/carolineverticchio/Desktop/reportingApp/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/carolineverticchio/Desktop/reportingApp/node_modules/express/lib/router/index.js:317:13)
    at /Users/carolineverticchio/Desktop/reportingApp/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/carolineverticchio/Desktop/reportingApp/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/carolineverticchio/Desktop/reportingApp/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/Users/carolineverticchio/Desktop/reportingApp/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/Users/carolineverticchio/Desktop/reportingApp/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/carolineverticchio/Desktop/reportingApp/node_modules/express/lib/router/index.js:317:13)
    --------------------
    at Protocol._enqueue (/Users/carolineverticchio/Desktop/reportingApp/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at Protocol.handshake (/Users/carolineverticchio/Desktop/reportingApp/node_modules/mysql/lib/protocol/Protocol.js:52:23)
    at PoolConnection.connect (/Users/carolineverticchio/Desktop/reportingApp/node_modules/mysql/lib/Connection.js:130:18)
    at Pool.getConnection (/Users/carolineverticchio/Desktop/reportingApp/node_modules/mysql/lib/Pool.js:48:16)
    at Promise.post (/Users/carolineverticchio/Desktop/reportingApp/node_modules/q/q.js:1181:36)
    at Promise.promise.promiseDispatch (/Users/carolineverticchio/Desktop/reportingApp/node_modules/q/q.js:808:41)
    at /Users/carolineverticchio/Desktop/reportingApp/node_modules/q/q.js:1411:14
    at runSingle (/Users/carolineverticchio/Desktop/reportingApp/node_modules/q/q.js:137:13)
    at flush (/Users/carolineverticchio/Desktop/reportingApp/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:112:11)
---------------------------------------------
    at Socket.Readable.on (_stream_readable.js:779:35)
    at PoolConnection.connect (/Users/carolineverticchio/Desktop/reportingApp/node_modules/mysql/lib/Connection.js:102:18)
    at Pool.getConnection (/Users/carolineverticchio/Desktop/reportingApp/node_modules/mysql/lib/Pool.js:48:16)
    at Promise.post (/Users/carolineverticchio/Desktop/reportingApp/node_modules/q/q.js:1181:36)
    at Promise.promise.promiseDispatch (/Users/carolineverticchio/Desktop/reportingApp/node_modules/q/q.js:808:41)
    at /Users/carolineverticchio/Desktop/reportingApp/node_modules/q/q.js:1411:14
    at runSingle (/Users/carolineverticchio/Desktop/reportingApp/node_modules/q/q.js:137:13)
    at flush (/Users/carolineverticchio/Desktop/reportingApp/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:112:11)
---------------------------------------------
    at requestTick (/Users/carolineverticchio/Desktop/reportingApp/node_modules/q/q.js:197:21)
    at Function.nextTick (/Users/carolineverticchio/Desktop/reportingApp/node_modules/q/q.js:180:13)
    at Promise.then (/Users/carolineverticchio/Desktop/reportingApp/node_modules/q/q.js:876:7)
    at /Users/carolineverticchio/Desktop/reportingApp/node_modules/kiddy/lib/kiddy.js:44:4
    at Function.promise (/Users/carolineverticchio/Desktop/reportingApp/node_modules/q/q.js:702:9)
    at Object.exports.touch (/Users/carolineverticchio/Desktop/reportingApp/node_modules/kiddy/lib/kiddy.js:42:11)
    at exports.getUsers (/Users/carolineverticchio/Desktop/reportingApp/lib/admin/controllers/admin.js:70:8)
    at Layer.handle [as handle_request] (/Users/carolineverticchio/Desktop/reportingApp/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/carolineverticchio/Desktop/reportingApp/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/carolineverticchio/Desktop/reportingApp/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/carolineverticchio/Desktop/reportingApp/node_modules/express/lib/router/layer.js:95:5)
    at /Users/carolineverticchio/Desktop/reportingApp/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/carolineverticchio/Desktop/reportingApp/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/carolineverticchio/Desktop/reportingApp/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/Users/carolineverticchio/Desktop/reportingApp/node_modules/express/lib/router/index.js:174:3)
---------------------------------------------
    at serveStatic (/Users/carolineverticchio/Desktop/reportingApp/node_modules/serve-static/index.js:115:12)
    at Layer.handle [as handle_request] (/Users/carolineverticchio/Desktop/reportingApp/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/carolineverticchio/Desktop/reportingApp/node_modules/express/lib/router/index.js:317:13)
    at /Users/carolineverticchio/Desktop/reportingApp/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/carolineverticchio/Desktop/reportingApp/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/carolineverticchio/Desktop/reportingApp/node_modules/express/lib/router/index.js:275:10)
    at /Users/carolineverticchio/Desktop/reportingApp/node_modules/less-middleware/lib/middleware.js:317:14
    at Layer.handle [as handle_request] (/Users/carolineverticchio/Desktop/reportingApp/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/carolineverticchio/Desktop/reportingApp/node_modules/express/lib/router/index.js:317:13)
    at /Users/carolineverticchio/Desktop/reportingApp/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/carolineverticchio/Desktop/reportingApp/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/carolineverticchio/Desktop/reportingApp/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/Users/carolineverticchio/Desktop/reportingApp/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/Users/carolineverticchio/Desktop/reportingApp/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/carolineverticchio/Desktop/reportingApp/node_modules/express/lib/router/index.js:317:13)
```

**Comment by KalenAnson** [comment]
Should be fixed in version 0.6
